TEL-3590 WIP on adding severity to exception threshold
hmrc/alert-config-builder pull request #44
Opened 2023-02-23 12:09 UTC by gavD

2023-02-23 13:53 UTC, sjpalf requested changes

2023-02-23 13:53 UTC, sjpalf commented on src/test/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilderSpec.scala
> +//    serviceConfig("errors-logged-severity") shouldBe JsString("warning")
did you mean to replace these with a different test?

2023-02-23 13:54 UTC, gavD commented on src/test/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilderSpec.scala
> +//    serviceConfig("errors-logged-severity") shouldBe JsString("warning")
sure did, will do now

2023-02-27 07:53 UTC, sjpalf approved these changes
<img src="https://media0.giphy.com/media/LSP1TCf9B2Aq6FnZAg/giphy.gif"/>

2023-02-27 07:53 UTC, merged